name: 'Build godzilla'
description: 'Build godzilla library'

inputs:
  ref:
    description: 'Name of the tag or branch to build'
    required: false
    default: 'main'
  install-prefix:
    description: 'Install prefix'
    required: true
  with-examples:
    description: 'Build with examples'
    required: false
    default: 'OFF'
  with-tests:
    description: 'Build with tests'
    required: false
    default: 'OFF'
  code-coverage:
    description: 'Build with code coverage'
    required: false
    default: 'OFF'


runs:
  using: "composite"
  steps:
    - run: |
        cd ${{ github.workspace }}
        curl -L -o godzilla-${{ inputs.ref }}.zip https://github.com/andrsd/godzilla/archive/refs/heads/${{ inputs.ref }}.zip
        unzip godzilla-${{ inputs.ref }}.zip
      shell: bash -el {0}

    - run: |
        mkdir -p ${{ github.workspace }}/godzilla-${{ inputs.ref }}/build
        cmake \
          -S ${{ github.workspace }}/godzilla-${{ inputs.ref }} \
          -B ${{ github.workspace }}/godzilla-${{ inputs.ref }}/build \
          -DCMAKE_INSTALL_PREFIX=${{ inputs.install-prefix }} \
          -DGODZILLA_BUILD_EXAMPLES=${{ inputs.with-examples }} \
          -DGODZILLA_BUILD_TESTS=${{ inputs.with-tests }} \
          -DGODZILLA_CODE_COVERAGE=${{ inputs.code-coverage }}
      shell: bash -el {0}

    - run: |
        cmake --build ${{ github.workspace }}/godzilla-${{ inputs.ref }}/build
      shell: bash -el {0}

    - run: |
        cmake --install ${{ github.workspace }}/godzilla-${{ inputs.ref }}/build
      shell: bash -el {0}
